version: '3'
services:

  capstone:  # db를 capstone으로 변경
    platform: linux/amd64
    container_name: capstone
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root1234
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  web:
    container_name: web
    build: .
    command: sh -c "python manage.py migrate --settings=capstone.settings.dev && python manage.py runserver 0.0.0.0:8000  --settings=capstone.settings.dev"
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      DATABASE_NAME: mysql
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: root1234
      DATABASE_PORT: 3306
      DATABASE_HOST: capstone  # db를 capstone으로 변경
      DJANGO_SETTINGS_MODULE: capstone.settings.dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - capstone  # db를 capstone으로 변경

volumes:
  app:
  dbdata:
